### ISSUE TITLE
critical bug forces nodes to crash

### ISSUE THREAD

**Issue by tpfuemp** [metaspartan/denarius#306]
when mining an empty block with fortunestake-address to burnaddress forces node to crash (and all others receiving this block)

https://github.com/metaspartan/denarius/blob/0696ef614e454156fa552a2944f712aa9e334868/src/main.cpp#L2967

wrong index for vtx-access - should be 0 , not 1 (memory segfault)

**Comment by metaspartan** [comment]
Resolved: https://github.com/metaspartan/denarius/commit/fac80b73e59d59a978c1ce40bd86952e95b16c11
